# Generated by Django 2.1 on 2018-11-23 16:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_fee', models.PositiveIntegerField()),
                ('hostel_fee', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('enter_date', models.DateField(default=datetime.date.today)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('fine', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=30)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('descrip', models.TextField(blank=True)),
                ('hostelpic', models.ImageField(blank=True, upload_to='hostels/')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('msg', models.TextField(blank=True)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propic', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('Class', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('phno', models.CharField(blank=True, max_length=20)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Hostel')),
                ('std_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Hostel')),
                ('warden_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Warden'),
        ),
        migrations.AddField(
            model_name='fees',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Student'),
        ),
    ]
